[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run prisma:generate && npm run build"

[deploy]
startCommand = "npm run prisma:migrate && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
aptPkgs = ["openssl"] 